apiVersion: apps/v1
kind: Deployment
metadata:
  name: maze-solver-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maze-solver-cloud
  template:
    metadata:
      labels:
        app: maze-solver-cloud
    spec:
      containers:
      - name: mazesolvercloud
        image: btpcontainerregistry.azurecr.io/mazesolvercloud:v5
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: btpcontainerregistrysecret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: maze-solver-cloud
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/maze-solver-cloud
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: maze-solver-cloud
  targetCPUUtilizationPercentage: 8