FROM continuumio/miniconda2

COPY environment.yml environment.yml

RUN conda env create --file environment.yml
RUN echo "source activate btpenv" > ~/.bashrc
ENV PATH /opt/conda/envs/env/bin:$PATH

COPY . .
ENTRYPOINT ['python', [maze_solver_cloud.py]]